# Generated by Django 2.2 on 2020-05-28 12:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200528_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cancel_expiry',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 5, 28, 12, 29, 9, 931640, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_date_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 5, 28, 12, 19, 9, 931640, tzinfo=utc)),
        ),
    ]
