# Generated by Django 2.2 on 2020-05-28 14:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200528_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cancel_expiry',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 5, 28, 14, 59, 4, 76591, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_date_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 5, 28, 14, 49, 4, 76591, tzinfo=utc)),
        ),
    ]
