# Generated by Django 2.2 on 2020-05-29 21:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200529_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cancel_expiry',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 5, 29, 21, 28, 10, 419572, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_date_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 5, 29, 21, 18, 10, 419572, tzinfo=utc)),
        ),
    ]
